name: Deploy Prebuilt React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Save and Restrict Permissions on Private Key
        run: |
          echo "${{ secrets.HOSTINGER_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 46.202.183.38 >> ~/.ssh/known_hosts

      - name: Deploy Prebuilt Static Files to Hostinger
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 46.202.183.38
          port: 65002
          username: u878508099
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY}}
          target: /public_html/react-one
          source: dist/*
          debug: true

      - name: Clean Up and Finalize on Hostinger
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: 46.202.183.38
          port: 65002
          username: u878508099
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          script: |
            cd /public_html/react-one
            echo "Deployment complete."
